In [1]:
import pandas as pd 
import numpy as np

from numpy import linalg

In [2]:
# Making the data
data={'Alp':[20,10,13,1,18,4],'Himalaya':[4,2,1,13,10,20],'Hawaii':[16,18,19,7,10,0],'Scuba':[0,10,7,19,2,16]}

In [3]:
# Changing the data to a dataframe
df=pd.DataFrame(data,index=['Anne','Bill','Chris','Jen','Joe','Maggie'])

In [4]:
df

Alp  Himalaya  Hawaii  Scuba
Anne     20         4      16      0
Bill     10         2      18     10
Chris    13         1      19      7
Jen       1        13       7     19
Joe      18        10      10      2
Maggie    4        20       0     16

In [5]:
#finding the covariance matrix

df.cov()

Alp   Himalaya     Hawaii  Scuba
Alp       56.8 -32.800000  32.800000  -56.8
Himalaya -32.8  54.666667 -54.666667   32.8
Hawaii    32.8 -54.666667  54.666667  -32.8
Scuba    -56.8  32.800000 -32.800000   56.8

In [7]:
# printing the eigenvalues

#lingalg.eigvals is use to find the eigenvalues and eigenvectors for the matrix

w,v= linalg.eig(df.cov())

print("printing eigenvalues: ")
print(w)

printing eigenvalues: 
[ 1.77101346e+02 -7.82978415e-15  4.58319875e+01  2.43716086e-15]


In [8]:
print("printing eigenvectors: ")
print(v)

printing eigenvectors: 
[[-5.08060809e-01  7.07106781e-01  4.91807091e-01  1.22865257e-01]
 [ 4.91807091e-01  2.39356232e-16  5.08060809e-01 -6.96350579e-01]
 [-4.91807091e-01 -2.93635201e-16 -5.08060809e-01 -6.96350579e-01]
 [ 5.08060809e-01  7.07106781e-01 -4.91807091e-01  1.22865257e-01]]


* As we have 2 dimensions in the data, there will be 2 eigenvectors and 2 corresponding eigenvalues.
* The two eigenvectors with the highest eigenvalues are taken as the principal components.

In [9]:
print([i[0] for i in v])
print([i[2] for i in v])

[-0.5080608089947458, 0.4918070905991539, -0.491807090599154, 0.5080608089947456]
[0.4918070905991543, 0.5080608089947456, -0.5080608089947457, -0.4918070905991539]


In [10]:
print(v.round())

[[-1.  1.  0.  0.]
 [ 0.  0.  1. -1.]
 [-0. -0. -1. -1.]
 [ 1.  1. -0.  0.]]


In [11]:
from sklearn.decomposition import PCA

In [12]:
n=2
pca = PCA(n_components=n)
pca.fit(df)

PCA(n_components=2)

In [13]:
print(pca.components_)

[[-0.50806081  0.49180709 -0.49180709  0.50806081]
 [ 0.49180709  0.50806081 -0.50806081 -0.49180709]]
