In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv('customer.csv')

In [3]:
df.sample(5)

age  gender review education purchased
26   53  Female   Poor        PG        No
41   23    Male   Good        PG       Yes
6    18    Male   Good    School        No
28   48    Male   Poor    School        No
27   69  Female   Poor        PG        No

In [4]:
df=df.iloc[:,2:] #gender doesnt have any order hence its nominal categorical data - one hot encoding
# review has good average and poor - its ordinal catergorical - ordinal encoding
# education = ordinal categorical  -  ordinal encoding
# purchased = nominal categorical  -one hot encoding

In [5]:
df.sample(5)

review education purchased
30  Average        UG        No
34  Average    School        No
16     Poor        UG       Yes
22     Poor        PG       Yes
13  Average    School        No

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder



X_train,X_test,y_train,y_test=train_test_split(df.drop('purchased',axis=1),df['purchased'],test_size=0.3, random_state=0)

In [7]:
X_train

review education
7      Poor    School
14     Poor        PG
45     Poor        PG
48     Good        UG
29  Average        UG
15     Poor        UG
30  Average        UG
32  Average        UG
16     Poor        UG
42     Good        PG
20  Average    School
43     Poor        PG
8   Average        UG
13  Average    School
25     Good    School
5   Average    School
17     Poor        UG
40     Good    School
49     Good        UG
1      Poor        UG
12     Poor    School
37  Average        PG
24  Average        PG
6      Good    School
23     Good    School
36     Good        UG
21  Average        PG
19     Poor        PG
9      Good        UG
39     Poor        PG
46     Poor        PG
3      Good        PG
0   Average    School
47     Good        PG
44  Average        UG

In [8]:
X_test

review education
28     Poor    School
11     Good        UG
10     Good        UG
41     Good        PG
2      Good        PG
27     Poor        PG
38     Good    School
31     Poor    School
22     Poor        PG
4   Average        UG
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School

In [9]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
#prefer giving in order so oe doesnt allot any random number 

In [10]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [11]:
X_train=oe.transform(X_train)
X_test=oe.transform(X_test)

In [12]:
X_train

array([[0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [1., 1.],
       [0., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [0., 1.],
       [2., 0.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [1., 2.],
       [2., 0.],
       [2., 0.],
       [2., 1.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.]])

In [13]:
X_test

array([[0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [1., 0.],
       [2., 0.]])

In [14]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [15]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()

In [16]:
le.fit(y_train)

LabelEncoder()

In [17]:
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [18]:
# do not use label encoder for input, it is for output class

In [19]:
y_train

array([1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])